Add do fgs_plan
DiamondLightSource/mx-bluesky pull request #140
Opened 2024-08-05 13:50 UTC by olliesilvester

Fixes #80 as part of https://github.com/orgs/DiamondLightSource/projects/6/views/1?pane=issue&itemId=73047222. This adds a slightly modified version of the `do_fgs` plan in Hyperion. Here, you can optionally device whether or not we need to do extra things - eg zocalo. This plan should be usable for VMXm, i03, i04, and hopefully other MX beamlines.

~The idea of the `level 1` folder is for it to be filled with plan stubs, i.e plans that cannot be ran on their own. I guess it could just be renamed to `plan_stubs`...~ I renamed it `plan_stubs`

To test:

- Check functionality is sensible, and compare to hyperion's do_fgs (https://github.com/DiamondLightSource/hyperion/blob/14421be796985f710129de1f105e2f1e65bf6a71/src/hyperion/experiment_plans/flyscan_xray_centre_plan.py#L329)
- Confirm tests are sufficient

2024-08-06 10:11 UTC, dperl-dls reviewed
I think we will probably want another level of categorisation than this, maybe put `do_fgs` into a gridscan module?

2024-08-12 19:40 UTC, DominicOram requested changes
Thanks, I think we can maybe keep them even more similar

2024-08-13 09:56 UTC, DominicOram commented on src/mx_bluesky/plan_stubs/do_fgs.py
> +        yield from post_plans()
So the wait for zocalo stage has the potential to take 2 seconds. I think maybe for the moment keep the `post_plans` bit and call it with a wait for stage on hyperion. I think it should be renamed to `during_collection_plans` though, as that's what it is

2024-08-20 12:36 UTC, olliesilvester commented on src/mx_bluesky/plan_stubs/do_fgs.py
> +        yield from pre_plans()
Agreed, but I also think `pre_plans` gives us a bit more flexibility in case we want to also read other hardware at this point

2024-08-20 12:40 UTC, DominicOram commented on src/mx_bluesky/plan_stubs/do_fgs.py
> +        yield from pre_plans()
I would suggest we don't build in complexity we don't yet need

2024-08-20 12:56 UTC, olliesilvester commented on src/mx_bluesky/device_setup_plans/read_hardware_for_setup.py
> +def read_hardware_for_zocalo(detector: EigerDetector):
Arguably I could just move all these plans in the same PR. I thought i'd try and separate it out a bit though, otherwise it will quickly spiral

2024-10-22 15:07 UTC, DominicOram requested changes
Sorry to put comments on this again. Is there a reason we didn't just put all of `kickoff_and_complete_gridscan` in common? I think it is common to all beamlines?

2024-10-22 15:07 UTC, DominicOram commented on src/mx_bluesky/common/device_setup_plans/read_hardware_for_setup.py
> +def read_hardware_for_zocalo(detector: EigerDetector):
Should: This read is also when zocalo is triggered, I think it's worth adding that into the docstring here

2024-10-22 15:07 UTC, DominicOram commented on src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
> +    def do_fgs_and_wait_for_zocalo_and_read_hardware():
Should: This doesn't wait for the zocalo results to be finished, that's done on the `trigger_and_read` of zocalo.

2024-10-22 15:07 UTC, DominicOram commented on src/mx_bluesky/common/plan_stubs/do_fgs.py
> +    yield from read_hardware_for_zocalo(detector)
Should: In re-reading the code I actually think we need to wait for the zocalo stage to be finished before we do this read, which will trigger the results to zocalo. We should do both during the collection

2024-10-22 15:23 UTC, olliesilvester commented
> Sorry to put comments on this again. Is there a reason we didn't just put all of `kickoff_and_complete_gridscan` in common? I think it is common to all beamlines?

No real reason, I was just trying to move bits incrementally, and wasn't sure about the Zocalo bits on other beamlines

2024-10-22 15:31 UTC, olliesilvester commented on src/mx_bluesky/common/device_setup_plans/read_hardware_for_setup.py
> +def read_hardware_for_zocalo(detector: EigerDetector):
Good catch, I didn't realise it did that!

2024-10-22 15:35 UTC, DominicOram commented
> > Sorry to put comments on this again. Is there a reason we didn't just put all of `kickoff_and_complete_gridscan` in common? I think it is common to all beamlines?
> 
> No real reason, I was just trying to move bits incrementally, and wasn't sure about the Zocalo bits on other beamlines

I agree about the zocalo stuff not being needed everywhere but I think the other decorators are common, and would be needed for nexus/ispyb writing

2024-10-22 16:01 UTC, olliesilvester commented
OK, I'll put the whole function in `common`

2024-10-23 11:05 UTC, olliesilvester commented on src/mx_bluesky/common/plan_stubs/do_fgs.py
> +    yield from read_hardware_for_zocalo(detector)
Hmm, the original code does the read before waiting for zocalo to stage
```
def do_fgs():
...
  yield from read_hardware_for_zocalo(eiger)
  LOGGER.info("Wait for all moves with no assigned group")
  yield from bps.wait()
  LOGGER.info("kicking off FGS")
  yield from bps.kickoff(gridscan, wait=True)
  gridscan_start_time = time()
  LOGGER.info("Waiting for Zocalo device queue to have been cleared...")
  yield from bps.wait(
  ZOCALO_STAGE_GROUP
   )  # Make sure ZocaloResults queue is clear and ready to accept our new data
```
But are you saying that Hyperion should also be doing the wait first?

2024-10-23 13:33 UTC, olliesilvester commented on src/mx_bluesky/common/plan_stubs/do_fgs.py
> +    yield from read_hardware_for_zocalo(detector)
As discussed, we should stage zocalo immediately after the detector is armed, and wait for it to finish before doing this read.

I've made https://github.com/DiamondLightSource/mx-bluesky/issues/590 but I may do it in this PR

2024-10-23 15:53 UTC, olliesilvester commented on src/mx_bluesky/common/plan_stubs/do_fgs.py
> +        plan_name (str):                        Used to check if Zocalo callback should be started in this plan,
This is pretty confusing to have in the plan stub. We are assuming Zocalo will always be triggered from this plan, so I think we should also make sure the ZocaloCallback is correctly configured just from this plan

2024-10-25 14:45 UTC, olliesilvester commented
I started to reshuffle some of the hyperion tests in `test_flyscan_xray_centre` to the common `test_do_fgs`, but this quickly led into me having to move the whole parameter model + all callbacks into common too, so that is a job for a separate ticket

2024-10-29 13:51 UTC, DominicOram requested changes
A couple of final questions around the tests but generally there.

2024-10-29 13:51 UTC, DominicOram commented on tests/unit_tests/common/plan_stubs/test_do_fgs.py
> +    with patch("mx_bluesky.common.plans.do_fgs.check_topup_and_wait_if_necessary"):
Nit: I have a mild preference for patch decorators as it reduces the indent a bit but not that bothered

2024-10-29 13:51 UTC, DominicOram commented on tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py
> +        fake_fgs_composite.eiger.filewriters_finished = finished_status
Could: You can use `ophyd.sim.NullStatus` here instead of making you're own finished status

2024-10-29 17:23 UTC, olliesilvester commented on tests/unit_tests/common/plan_stubs/test_do_fgs.py
> +        assert len(null_messages) == 0
Whoops, nothing anymore! I think I meant to remove this

2024-10-30 09:07 UTC, olliesilvester commented on tests/unit_tests/common/plan_stubs/test_do_fgs.py
> +def test_kickoff_and_complete_gridscan_with_run_engine_correct_documents(
Yep, agreed. I did start to do this, but then it lead to having to move the callbacks to common, which requires also moving the parameters + constants to common, so I reverted. Anyway, I'll add a comment saying to change this test once the zocalo callbacks have been moved

2024-10-30 10:20 UTC, merged