Merge Hyperion into MX-Bluesky
DiamondLightSource/mx-bluesky pull request #172
Opened 2024-08-21 14:11 UTC by dperl-dls

2024-08-23 09:17 UTC, noemifrisina reviewed
Looks like a good start, thank you! 

I think it's fine to drop python3.10, asaik the other applications are using 3.11 anyway so don't see the point in getting the hyperion code to work with 3.10.

It would be good to agree on the priority of the TODOs and open issues for them. Also I'd add this to the list: https://github.com/DiamondLightSource/mx-bluesky/blob/86dc96ca97f204e26cf43a5bad9420d560a08ff7/docs/developer/general/explanations/decisions/0002-repository-structure.rst?plain=1#L44

2024-08-23 09:48 UTC, olliesilvester commented
The commits here are the unsquashed versions of Hyperion. Not a huge deal though, as we only recently moved to using squashed commits in Hyperion

2024-08-23 09:52 UTC, olliesilvester requested changes
I would prefer if the commit history was preserved to the squashed version, but if that's too much effort then I'm happy to approve, since this is currently blocking any more Hyperion development. We should create new tickets for the remaining things to do as well, and try out deployment fairly quickly

2024-08-23 09:53 UTC, dperl-dls commented
It does have the squashed versions of the ones which were squashed

2024-08-23 09:58 UTC, olliesilvester approved these changes

2024-08-27 10:28 UTC, noemifrisina approved these changes

2024-08-28 08:11 UTC, rtuck99 commented on pyproject.toml
> +    "matplotlib",
matplotlib is no longer optional

2024-08-28 08:16 UTC, rtuck99 commented on pyproject.toml
> +    "ophyd-async",
ditto

2024-08-28 08:17 UTC, rtuck99 commented on pyproject.toml
> +    "black",
duplicate line

2024-08-28 08:25 UTC, rtuck99 commented on pyproject.toml
> +
requires-python should be 3.11

2024-08-28 08:53 UTC, rtuck99 approved these changes
Approved, please fix minor things with `pyproject.toml`

2024-08-28 10:12 UTC, merged