Update pydantic and ophyd_async to latest versions
DiamondLightSource/mx-bluesky pull request #456
Opened 2024-09-06 08:55 UTC by DominicOram

Fixes #454

To test:
* Confirm unit tests pass

2024-09-06 16:12 UTC, olliesilvester requested changes
Looks OK I think. The linting is failing because of the recent change to `detector.py` in `dodal`. We just need to remove the line 

```
beam_xy_converter=DetectorDistanceToBeamXYConverter(
                self.det_dist_to_beam_converter_path
            ),
```

from `class RotationExperiment`

2024-09-06 16:15 UTC, DominicOram commented
> Looks OK I think. The linting is failing because of the recent change to detector.py in dodal. We just need to remove the line...

You mean like https://github.com/DiamondLightSource/mx-bluesky/pull/456/commits/04a006e38b309061983d9eb9fa23e55fafdcf631 ;)

2024-09-06 16:17 UTC, olliesilvester approved these changes
OK, looks good!

2024-09-06 16:20 UTC, merged

2024-09-06 16:20 UTC, olliesilvester commented
Yeah, I wasn't 100% on why a few of the changes were made but they looked sensible enough

2024-09-09 15:01 UTC, DominicOram commented on src/mx_bluesky/hyperion/parameters/components.py
>              return version
Thanks, spun into https://github.com/DiamondLightSource/mx-bluesky/issues/461