Update I24 serial docs
DiamondLightSource/mx-bluesky pull request #487
Opened 2024-09-13 15:07 UTC by noemifrisina

2024-09-13 15:30 UTC, noemifrisina commented on docs/developer/serial-crystallography-on-i24/how-to/run-a-collection.rst
> +map (if applicable) will still be saved in the data directory at collection time.
In general, I agree with just describing the latest version. In this case, I am a bit worried as scientists and users have been used until now to having to press the set parameters button for the collection to work. I think it may be worth leaving the comment for a bit while the staff gets used to it and then remove it at a later time...

2024-09-13 16:54 UTC, noemifrisina commented on docs/developer/serial-crystallography-on-i24/project-planning/roadmap.rst
> +     - Jan. 25
Yeah, here I was referring only to converting the current set up code into bluesky plans but admittedly I wasn't very clear. I'll rephrase and specify that it's dependent on those issues being completed first

2024-09-13 17:08 UTC, noemifrisina commented on docs/developer/serial-crystallography-on-i24/project-planning/roadmap.rst
> +8. Reinstate full mapping code using bluesky.
Integrating Panda, yes, at least for the fixed target, but I have no idea yet of a possible timeline so I was going to add it at a later time.

2024-09-24 11:55 UTC, DominicOram commented on docs/developer/serial-crystallography-on-i24/project-planning/roadmap.rst
> +8. Reinstate full mapping code using bluesky.
A comment to that affect would be good

2024-09-24 12:02 UTC, DominicOram requested changes
One comment in "code" and I also think it would be good to mention the panda somewhere here. Otherwise good, thanks.

2024-09-24 12:02 UTC, DominicOram commented on docs/developer/serial-crystallography-on-i24/project-planning/roadmap.rst
> +     - :material-regular:`pending;2em`
I believe `coniql` is now not what we want to use, I'm discussing with people at https://diamondlightsource.slack.com/archives/C06BBH6LX6U/p1727179118445009

2024-09-25 12:04 UTC, DominicOram approved these changes
Great, thanks!

2024-09-25 12:10 UTC, merged