Only use config server if GDA didn't supply params
DiamondLightSource/mx-bluesky pull request #496
Opened 2024-09-16 17:19 UTC by olliesilvester

2024-10-10 13:08 UTC, dperl-dls requested changes

2024-10-10 13:08 UTC, dperl-dls commented on src/mx_bluesky/hyperion/parameters/gridscan.py
> +            values["use_gpu"] = cls.features.best_effort().use_gpu_for_gridscan
Should: Only fetch the flags from the server once and only define them in one place.

With something like:

```suggestion
    def set_default_feature_flags(cls, values) -> Any:
        cls.features = FeatureFlags.best_effort()
        if "use_panda" in values:
            cls.features.use_panda_for_gridscan = values["use_panda"]
        ...
```

then the new definitions above could be removed?

2024-10-14 10:40 UTC, olliesilvester commented on src/mx_bluesky/hyperion/parameters/gridscan.py
> +            values["use_gpu"] = cls.features.best_effort().use_gpu_for_gridscan
I agree to only get the flags from the server once, but I think the definitions for, eg `use_panda` still need to be in `GridCommon`, just having them in the validator isn't enough for pydantic to know that `GridCommon` has these attributes

2024-10-21 10:20 UTC, dperl-dls commented on src/mx_bluesky/hyperion/parameters/gridscan.py
> +            values["use_gpu"] = cls.features.best_effort().use_gpu_for_gridscan
oh, of course, sorry. but `use_panda` still shouldn't be in `GridCommon`, the flags should be passed in in `features`, which is a `BaseModel`
in the validator for `features` you can then start with FeatureFlags.best_effort() and update anything which is passed in

2024-10-21 13:57 UTC, olliesilvester commented on src/mx_bluesky/hyperion/parameters/gridscan.py
> +            values["use_gpu"] = cls.features.best_effort().use_gpu_for_gridscan
Okay, that works, does that mean we should change the logic of `best_effort`? Right now it checks the URL and uses the constants if it cant find anything. But best efforts should
1. Check if GDA supplied values for each parameter, if yes then use that
2. Check if parameter exists in URL, if yes then use that
3. Use Hyperion constants as a last resort

Is that reasonable?

2024-10-22 12:49 UTC, dperl-dls commented on src/mx_bluesky/hyperion/parameters/gridscan.py
> +            values["use_gpu"] = cls.features.best_effort().use_gpu_for_gridscan
I don't think you need to change the logic in `best_effort` to achieve that priority order, just set the defaults in teh `FeatureFlags` class to the constants. maybe add a new layer to `I03Constants` to hold defaults for feature flags.

2024-10-22 12:52 UTC, dperl-dls commented on src/mx_bluesky/hyperion/parameters/gridscan.py
> +            values["use_gpu"] = cls.features.best_effort().use_gpu_for_gridscan
but if you want to add the ability to override stuff in best_effort with kwargs that sounds fine to me

2024-10-22 12:54 UTC, olliesilvester commented on src/mx_bluesky/hyperion/parameters/gridscan.py
> +            values["use_gpu"] = cls.features.best_effort().use_gpu_for_gridscan
I think we still want GDA parameters to have priority. We use `best_effort` in our plans so these should also give us the GDA parameters when they're supplied

2024-10-24 12:03 UTC, olliesilvester commented on src/mx_bluesky/hyperion/parameters/gridscan.py
> +            values["use_gpu"] = cls.features.best_effort().use_gpu_for_gridscan
I think I've changed my mind actually, I think the config server should take priority once it's actually being used

2024-10-25 14:04 UTC, dperl-dls approved these changes
This is great, thanks for reworking it! Minor comments about the comments, up to you

2024-10-25 14:55 UTC, merged