I24 ssx: Use updated PMAC ProgramRunner
DiamondLightSource/mx-bluesky pull request #501
Opened 2024-09-17 12:48 UTC by noemifrisina

Use PMAC ProgramRunner kickoff and complete to run the fixed target collection.

Needs [Dodal#788](https://github.com/DiamondLightSource/dodal/pull/792)

2024-09-20 15:34 UTC, DominicOram requested changes
Thanks, couple of issues in the code

2024-09-20 15:34 UTC, DominicOram commented on src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Collect_py3v1.py
>      else:
Could: This `else` statement is redundant as you have the early return.

2024-09-20 15:34 UTC, DominicOram commented on src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Collect_py3v1.py
> -                raise ValueError(msg)
Should: This has been broken for 7 years? I feel like at this point we should remove it and then re-introduce when it actually does get added back.

2024-09-20 15:34 UTC, DominicOram commented on src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Collect_py3v1.py
>  def get_prog_num(
Could: I feel like the test against this could be improved a bit given we're editing the function quite a lot. It doesn't test all combinations and uses integers rather than enums

2024-09-20 15:34 UTC, DominicOram commented on src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Collect_py3v1.py
> +    # Get program number
Nit: This comment just repeats what the line below it says, it doesn't feel like it adds much value

2024-09-20 15:34 UTC, DominicOram commented on src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Collect_py3v1.py
> +        parameters (FixedTargerParameters): The collection paramelters.
```suggestion
        parameters (FixedTargerParameters): The collection parameters.
```

2024-09-20 15:42 UTC, noemifrisina commented on src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Collect_py3v1.py
> -                raise ValueError(msg)
Made a separate issue for it because there's a lot of code that raises this error if full mapping is selected, plus the edm bits to be removed, see #515 . Link added in code

2024-09-23 12:04 UTC, DominicOram approved these changes
Great, thanks!

2024-09-23 14:38 UTC, merged