Add sleep to gridscan validity check
DiamondLightSource/mx-bluesky pull request #503
Opened 2024-09-17 15:51 UTC by olliesilvester

Fixes #502 (maybe...)

Other option is to wait for PV to be archived and wait to see the error again

2024-09-18 10:10 UTC, DominicOram requested changes
Thanks, couple of comments, I think we need a bit more testing on the beamline

2024-09-19 10:38 UTC, olliesilvester commented on src/mx_bluesky/hyperion/device_setup_plans/setup_panda.py
> +PULSE_WIDTH_US = 50
Ah, accidentally kept this change from https://github.com/DiamondLightSource/mx-bluesky/pull/498

2024-09-19 10:40 UTC, olliesilvester commented on src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
> +    yield from bps.sleep(0.1)
Yeah, I can try and test this on a Tuesday, I guess by forcing Hyperion to go from valid to invalid params every time. The scan invalid PV is added to the archiver too now, which should help

2024-10-10 14:51 UTC, closed without merging

2024-10-10 14:51 UTC, olliesilvester commented
Pretty sure this is caused by https://jira.diamond.ac.uk/browse/I03-993. so no need for the sleep