470 Full experiment plan to replace execute request
DiamondLightSource/mx-bluesky pull request #538
Opened 2024-09-30 10:41 UTC by rtuck99

This fix addresses #470 

It also requires GDA jython script change (gerrit change request TBC)

To test:

Confirm unit tests pass, and additional system test `test_load_centre_collect_full_plan` work
This code change should support single and multiple rotations, and will be enabled if the property
`gda.mx.hyperion.load_centre_collect.enabled` is set to `true` in domain.properties

2024-09-30 17:17 UTC, DominicOram requested changes
This is great, thank you! I think the only major issue is the `WarningException` thing otherwise just cleaning up. I think the failing test and some of the linting can be fixed by https://github.com/DiamondLightSource/mx-bluesky/pull/506/files.

2024-09-30 17:17 UTC, DominicOram commented on tests/unit_tests/hyperion/experiment_plans/test_load_centre_collect_full_plan.py
> +def dont_find_pin(pin_tip_detection):
Should: I don't think this is used? Can we remove it?

2024-09-30 17:17 UTC, DominicOram commented on tests/system_tests/hyperion/external_interaction/test_load_centre_collect_full_plan.py
> +    assert truncated_comment == expected_comment
Should: Are these exactly the same as those in `test_ispyb_dev_connection.py`? Can we move them to somewhere common?

2024-09-30 17:17 UTC, DominicOram commented on tests/system_tests/hyperion/external_interaction/test_load_centre_collect_full_plan.py
> +def test_execute_load_centre_collect_full_plan(
Must: Running this I get an error:
```
FAILED tests/system_tests/hyperion/external_interaction/test_load_centre_collect_full_plan.py::test_execute_load_centre_collect_full_plan - AssertionError: 
  expected beamSizeAtSampleX 0.1 == 0.02
  
assert '\nexpected beamSizeAtSampleX 0.1 == 0.02\n' == '\n'
  
  Strings contain only whitespace, escaping them using repr()
  - '\n'
  + '\nexpected beamSizeAtSampleX 0.1 == 0.02\n'
```

2024-09-30 17:17 UTC, DominicOram commented on tests/system_tests/hyperion/external_interaction/test_load_centre_collect_full_plan.py
> +def test_execute_load_centre_collect_full_plan(
Otherwise, love this test though, thank you!

2024-09-30 17:44 UTC, DominicOram commented on src/mx_bluesky/hyperion/experiment_plans/load_centre_collect_full_plan.py
> +        oav_params = OAVParameters(context="xrayCentring")
https://github.com/DiamondLightSource/mx-bluesky/issues/314

2024-09-30 17:47 UTC, DominicOram commented on src/mx_bluesky/hyperion/parameters/components.py
> +    detector_distance_mm: float | None = Field(default=None, gt=0)
https://github.com/DiamondLightSource/mx-bluesky/issues/540

2024-09-30 17:49 UTC, DominicOram commented on src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
> +                xray_centre = initial_xyz
https://github.com/DiamondLightSource/mx-bluesky/issues/541

2024-10-02 10:38 UTC, rtuck99 commented on src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
> +    finally:
I will look at doing this for the multipin changes as I will need to move that anyway

2024-10-02 12:43 UTC, rtuck99 commented on tests/system_tests/hyperion/external_interaction/conftest.py
> +    )
The two fixtures use different sets of devices - `oav_for_system_test` and `undulator_for_system_test`

2024-10-02 13:06 UTC, rtuck99 commented on tests/unit_tests/hyperion/experiment_plans/test_load_centre_collect_full_plan.py
> +    return set_good_position
`dont_find_pin` isn't used anyway as in the end I rewrote the test using the run engine simulator so I will remove it

2024-10-02 13:12 UTC, rtuck99 commented on tests/system_tests/hyperion/external_interaction/test_load_centre_collect_full_plan.py
> +    assert truncated_comment == expected_comment
Yes, I have moved them

2024-10-04 15:34 UTC, DominicOram commented on tests/unit_tests/hyperion/experiment_plans/test_load_centre_collect_full_plan.py
> +    return set_good_position
I still think the use of `partial` and `AsyncStatus` is cleaner than the nested functions and `NullStatus` but not worth holding things up on

2024-10-07 10:11 UTC, merged