Adds a box width parameter that can be passed to grid detect
DiamondLightSource/mx-bluesky pull request #542
Opened 2024-09-30 18:26 UTC by DominicOram

Goes some way to #231 but should try again on the beamline

## To test
* Confirm tests pass

2024-10-24 16:55 UTC, DominicOram commented
I think given it will be a while before we can test this we review/merge with the idea of checking if we think it will fix the issue and retest next run

2024-10-28 16:17 UTC, olliesilvester requested changes
Changes look good, but from @rtuck99's comment on https://github.com/DiamondLightSource/mx-bluesky/issues/231, I'm not 100% sure if this will work

From my understanding, after doing FGS, Hyperion sets the aperture size based off the bounding box size returned from Zocalo. The bounding box size is in units of box size, but where do we tell Zocalo about the box size?

Also, we should define box size and bbox size somewhere, I got confused about it just now

2024-11-05 14:35 UTC, DominicOram commented
> Changes look good, but from @rtuck99's comment on #231, I'm not 100% sure if this will work
> 
> From my understanding, after doing FGS, Hyperion sets the aperture size based off the bounding box size returned from Zocalo. The bounding box size is in units of box size, but where do we tell Zocalo about the box size?
> 
> Also, we should define box size and bbox size somewhere, I got confused about it just now

I agree with this but the bounding box code is also in flux with https://github.com/DiamondLightSource/mx-bluesky/pull/553 at the moment. To avoid merge conflicts on that (already big) PR I have made https://github.com/DiamondLightSource/mx-bluesky/issues/618

2024-11-11 13:36 UTC, olliesilvester approved these changes

2024-11-11 13:51 UTC, merged