(#475) Xray-centre and collect on multiple centres
DiamondLightSource/mx-bluesky pull request #553
Opened 2024-10-04 15:04 UTC by rtuck99

Implements #475 

Requires 
~DiamondLightSource/dodal#814~
DiamondLightSource/dodal#858 and
DiamondLightSource/mx-bluesky#593

This implements multiple rotations on multiple centres for the `load_centre_collect_full_plan`.
The behaviour of other plans should remain unchanged, with moving to a single centre.
By default load_centre_collect also only does a single centre.
To specify multiple centres, include the following in the request parameters:

```
  "select_centres": {
    "name": "top_n_by_max_count",
    "n": 5
  },
```

where n is however many centres to select

2024-10-04 17:42 UTC, DominicOram requested changes
Thank you! This is great, we will see how it goes on Monday. Some comments in code, think a few places where we should probably all talk it through together.

Additionally, for multipin tests we're also probably going to need something that gives us the top result in each segment e.g. for a 100 box long multipin with 5 samples in we would want the top result in 0-20, 20-40 etc. We can do this on the beamline for the tests next week and then maybe pull it into a better defined issue.

2024-10-04 17:42 UTC, DominicOram commented on src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
> +def flyscan_xray_centre(
I wonder if we should have a new place for "top level" plans, which is what this is really. It's hard to differentiate between this and `flyscan` and when you would use one and not the other. Probably needs a wider discussion

2024-10-04 17:42 UTC, DominicOram commented on src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
> +def _xrc_result_to_flyscan_result(
Should: I think it is cleaner, and more idiomatic of bluesky, to move this calculation to the `FlyscanEventHandler`. It should be able to get everything it needs for the calculation by the events produced throughout the plan. This would reduce the complexity of the plans themselves and change `_fire_flyscan_result_event` to just be a `bps.read(zocalo)` Probably needs a discussion.

2024-10-04 17:42 UTC, DominicOram commented on src/mx_bluesky/hyperion/experiment_plans/load_centre_collect_full_plan.py
> +    assert callable(selection_func)
Should: I don't think letting the user provide a function name like this is very good. It's quite brittle to name changes/argument changes and I don't think we need this much flexibility right now anyway.

2024-10-04 17:42 UTC, DominicOram commented on src/mx_bluesky/hyperion/experiment_plans/load_centre_collect_full_plan.py
> +        )
Must: I think what we actually want to do is take all the hits and wrap them up in one call to `multi_rotation_scan` with different x/y/z starts. Otherwise we're going to get the detector re-arming between them all etc. For a first pass this probably means just stay at the same aperture for each of them, which is fine.

2024-10-04 17:42 UTC, DominicOram commented on src/mx_bluesky/hyperion/experiment_plans/pin_centre_then_xray_centre_plan.py
> +    # TODO listen for flyscan results and then centre
Should: We're doing this, no need for the comment

2024-10-04 17:42 UTC, DominicOram commented on src/mx_bluesky/hyperion/experiment_plans/pin_centre_then_xray_centre_plan.py
> +    flyscan_event_handler = FlyscanEventHandler()
Should: This pattern is used quite a bit now, I think it's probably worth making a wrapper of something like:
```python
def do_plan_and_move_to_xrc_result(plan):
    """Do the specified plan then move to whatever result XRC gives back"""
    yield from bpp.subs_wrapper(plan, flyscan_event_handler := FlyscanEventHandler())
    flyscan_results = flyscan_event_handler.flyscan_results
    assert (
        flyscan_results
    ), "Flyscan result event not received or no crystal found and exception not raised"
    yield from change_aperture_then_centre(flyscan_results[0], composite)
```

2024-10-07 08:08 UTC, rtuck99 commented on src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
> +class FlyscanEventHandler:
I think it's overkill for what should just be a simple event handler. What does it give us?

2024-10-07 08:12 UTC, rtuck99 commented on src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
> +def flyscan(
Hmm I think we should have a conversation about terminology and the use of the word "centring"

2024-10-07 08:22 UTC, rtuck99 commented on src/mx_bluesky/hyperion/experiment_plans/pin_centre_then_xray_centre_plan.py
> +    flyscan_event_handler = FlyscanEventHandler()
I didn't partly as we are ultimately removing most of the places where it's used anyway

2024-10-15 12:26 UTC, rtuck99 commented on src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
> +def _xrc_result_to_flyscan_result(
I started doing this and have run into complications with unit tests as now `ThreeDGridscan` needs to be injected in lots of places. Also I think I have run into additional complications due to #220 which previously wasn't an issue because the tests either didn't need to account for this bug or did it both ways which cancelled each other out.

2024-11-04 18:17 UTC, DominicOram requested changes
Sorry this has taken me so long to get around to, some comments in code

2024-11-04 18:17 UTC, DominicOram commented on tests/unit_tests/hyperion/experiment_plans/test_change_aperture_then_move_plan.py
> +    )
Should: Probably want to add `msg.obj == aperture_scatterguard` here

2024-11-04 18:17 UTC, DominicOram commented on tests/unit_tests/hyperion/experiment_plans/test_change_aperture_then_move_plan.py
> +        and msg.obj.name == "smargon-x"
Nit: I think it's nicer to use `msg.obj== smargon.x` here as it makes it easier to pick up with the IDE where the smargon is being used

2024-11-04 18:17 UTC, DominicOram commented on tests/unit_tests/hyperion/experiment_plans/test_experiment_registry.py
> +@pytest.mark.skip(reason="Conflicting MsgGenerator import strangeness")
Should: Could we link to an issue that will fix, maybe it's covered by https://github.com/DiamondLightSource/mx-bluesky/pull/564?

2024-11-04 18:17 UTC, DominicOram commented on tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py
> +                    event_doc.set_result(doc["xray_centre_results"])
Could: Could we just use the real handler here and have this as more of an integration test?

2024-11-04 18:17 UTC, DominicOram commented on tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py
> +        # )
Should: Why is this commented out? If it's broken can we at least point to an issue fixing it or ideally fix in this PR

2024-11-04 18:17 UTC, DominicOram commented on tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py
> -    async def test_given_gridscan_fails_to_centre_then_stub_offsets_not_set(
Should: I think we still need a test that the stub offsets aren't set when we fail to diffract

2024-11-04 18:17 UTC, DominicOram commented on tests/unit_tests/hyperion/experiment_plans/test_load_centre_collect_full_plan.py
> +    # XXX sample test file xyz conflicts with detected xyz
Should: I'm not sure what this comment is trying to tell me?

2024-11-04 18:17 UTC, DominicOram commented on tests/unit_tests/hyperion/experiment_plans/test_pin_centre_then_xray_centre_plan.py
> +        lambda _, __, ___: _fire_xray_centre_result_event(
Nit: 
```suggestion
        lambda *_: _fire_xray_centre_result_event(
```

2024-11-05 14:17 UTC, DominicOram commented on src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
> +def _xrc_result_to_flyscan_result(
I think the real way to fix this is actually https://github.com/DiamondLightSource/python-dlstbx/issues/255

2024-11-05 14:41 UTC, DominicOram commented on src/mx_bluesky/hyperion/experiment_plans/change_aperture_then_move_plan.py
> +    # TODO confirm correction factor see mx-bluesky 231
Should: I've actually spun this into https://github.com/DiamondLightSource/mx-bluesky/issues/618 to avoid merge conflicts

2024-11-07 16:49 UTC, rtuck99 commented on src/mx_bluesky/hyperion/experiment_plans/flyscan_xray_centre_plan.py
> +                ]
`GridscanISPyBCallback` does also get the XrcResults through an event document via a call to `get_processing_results_from_event()`, and it sends the grid coordinates to ispyb.

I think both types have value - the grid coordinates are of interest if you are interested in the gridscan analysis pipeline, and are quite useful if correlating to the annotated snapshot.

The absolute mm coordinates are needed for moving to the centre but are kind of useless on their own to an end user without a frame of reference.

2024-11-08 09:48 UTC, rtuck99 commented on src/mx_bluesky/hyperion/experiment_plans/common/xrc_result.py
> +    raise ValueError(f"Invalid selection function {name}")
I can sort of do this but slightly uglier as Pydantic doesn't allow polymorphism with base classes - the fields have to be a type union instead.

2024-11-08 11:35 UTC, rtuck99 commented on tests/system_tests/hyperion/external_interaction/conftest.py
> +        )
I think one of them comes from the ophyd-async changes merge and the other one was from this PR, as they both depended on the dodal changes  - I'll rationalise them.

2024-11-08 11:40 UTC, rtuck99 commented on tests/system_tests/hyperion/external_interaction/conftest.py
> +def generate_xrc_result_event(device_name: str, test_results: Sequence[dict]) -> dict:
ditto

2024-11-08 13:41 UTC, rtuck99 commented on tests/unit_tests/hyperion/experiment_plans/test_flyscan_xray_centre_plan.py
> +        # )
We used to set the stub offsets as part of the centring, I seem to remember we discussed this and decided to remove it as they are not used on i03.

I will remove the commented out code

2024-11-08 13:59 UTC, rtuck99 commented on tests/unit_tests/hyperion/experiment_plans/test_load_centre_collect_full_plan.py
> +    # XXX sample test file xyz conflicts with detected xyz
The sample params file specifies x,y,z coordinates (because the model allows this). Whereas the plan gets the coordinates from the detected centres. I've added this to https://github.com/DiamondLightSource/mx-bluesky/issues/563 and will link in a comment

2024-11-20 12:24 UTC, DominicOram commented on tests/system_tests/hyperion/external_interaction/conftest.py
> +        )
I think this is the one that's not used so I will remove it

2024-11-20 12:31 UTC, DominicOram commented on tests/unit_tests/hyperion/experiment_plans/test_load_centre_collect_full_plan.py
> +    expected_rotation_scans = [
Nit: This is a bit verbose, I took the liberty of cleaning it up a little

2024-11-20 13:15 UTC, DominicOram approved these changes
Great, thank you!

2024-11-22 13:30 UTC, merged