Tidy up i24 serial logs
DiamondLightSource/mx-bluesky pull request #572
Opened 2024-10-15 14:15 UTC by noemifrisina

2024-10-25 10:52 UTC, noemifrisina commented
Deferred to after #573 is done and running on the beamline because of permission problems if run by staff/users

2024-11-04 11:23 UTC, olliesilvester requested changes
I know this wasn't actually finished yet, but I've added some comments anyway

2024-11-04 11:39 UTC, noemifrisina commented on src/mx_bluesky/beamlines/i24/serial/log.py
> +    # dodal_logger.removeHandler(dodal_logger.handlers[0])
That was accidentally commented out, sorry, fixed it now

2024-11-04 11:43 UTC, noemifrisina commented on src/mx_bluesky/beamlines/i24/serial/log.py
> +def setup_collection_logs(expt: str, dev_mode: bool = False) -> MsgGenerator:
As this is not the only start up bit that will need changing in the future, between web GUIs and once we get a cluster, I'm going to write a bigger ticket to include all the changes needed, this one included.

2024-11-05 09:59 UTC, olliesilvester approved these changes
Thanks, added some small comments. There are quite a few lines with no test coverage, but I will approve anyway as I know you're keen to test a release today.

A lot of the the untested lines are logging statements, I'd suggest testing them using by setting up logging in `pytest_runtest_setup(item)` in an i24 conftest, similiar to what we have in `mx-bluesky/tests/conftest.py`. Then we can easily assert logging calls after a`@patch("mx_bluesky.beamlines.i24.serial.log.SSX_LOGGER")`

2024-11-05 09:59 UTC, olliesilvester commented on src/mx_bluesky/beamlines/i24/serial/log.py
> +SSX_LOGGER.addHandler(logging.NullHandler())
What's the `NullHandler` for?

2024-11-05 09:59 UTC, olliesilvester commented on src/mx_bluesky/beamlines/i24/serial/log.py
>  def _get_logging_file_path() -> Path:
I think we might have already discussed this, but I can't remember. How come this needs to be in a different location to that given by the common util function (`/dls_sw/{beamline}/logs/bluesky/)`?

2024-11-05 09:59 UTC, olliesilvester commented on src/mx_bluesky/beamlines/i24/serial/run_fixed_target.sh
> -echo "Edm screen closed, bye!"
no more `bye!` :(

2024-11-05 10:10 UTC, noemifrisina commented on src/mx_bluesky/beamlines/i24/serial/log.py
>  def _get_logging_file_path() -> Path:
SO that users/staff can access it, this is the logger that looks like the old output they are used to. May not be needed for long, but for the moment it's useful for debugging

2024-11-05 10:10 UTC, noemifrisina commented on src/mx_bluesky/beamlines/i24/serial/run_fixed_target.sh
> -echo "Edm screen closed, bye!"
Well... it's three lines or so later :)

2024-11-05 11:14 UTC, merged