DNM Fixes for ophyd async types mega merge
DiamondLightSource/mx-bluesky pull request #593
Opened 2024-10-24 13:48 UTC by rtuck99

Fixes for compatibility with 
bluesky/ophyd-async#594

Depends on DiamondLightSource/dodal#858, DiamondLightSource/dodal#814

2024-10-28 14:06 UTC, dperl-dls commented
Turns out this is because of plotting code in `src/mx_bluesky/beamlines/i24/serial/fixed_target/i24ssx_Chip_Mapping_py3v1.py`

2024-11-04 14:03 UTC, DominicOram requested changes
Great, thanks. Minor comment

2024-11-04 15:25 UTC, rtuck99 commented on src/mx_bluesky/hyperion/experiment_plans/pin_tip_centring_plan.py
> +        return (int(tip_xy_px[0]), int(tip_xy_px[1]))
The reason I added it was because `move_pin_into_view` is defined as returning `Pixel` which is `tuple[int, int]` 
whereas `trigger_and_return_pin_tip()` now returns an instance of `Tip` which is defined as `Array1D[np.int32]` and whilst they are interchangeable for most purposes they aren't exactly the same type.
Notably == operator does not work the same for them, but I have also been bitten in the past when numpy primitives get laundered into variables that should be python natives.

2024-11-04 20:48 UTC, DominicOram commented on src/mx_bluesky/hyperion/experiment_plans/pin_tip_centring_plan.py
> +        return (int(tip_xy_px[0]), int(tip_xy_px[1]))
Great, thanks

2024-11-04 20:53 UTC, DominicOram approved these changes

2024-11-05 12:26 UTC, rtuck99 commented on src/mx_bluesky/hyperion/experiment_plans/pin_tip_centring_plan.py
> +        return (int(tip_xy_px[0]), int(tip_xy_px[1]))
test added

2024-11-05 13:32 UTC, merged