651 energy change fixes
DiamondLightSource/mx-bluesky pull request #676
Opened 2024-11-26 11:07 UTC by rtuck99

This fixes energy change issues discovered during beamline testing #651 

See also DiamondLightSource/dodal#918

1. Energy changes should now result in the VFM yaw and lateral position (x-offset) being set depending on the mirror stripe.
Previously the yaw was unset and the lateral position adjusted according to a lookup-table that was effectively single-valued.
2. The energy change, and individual DCM changes are now serialized because they cannot be done in parallel
3. The timeouts for the yaw, lat operations are increased to 30s from 10s

### Instructions to reviewer on how to test:
1. Energy changes work on beamline
2. Unit tests pass

### Checks for reviewer
- [ ] Would the PR title make sense to a scientist on a set of release notes
- [ ] If a new device has been added does it follow the [standards](https://diamondlightsource.github.io/dodal/main/reference/device-standards.html)
- [ ] If changing the API for a pre-existing device, ensure that any beamlines using this device have updated their Bluesky plans accordingly
- [ ] Have the connection tests for the relevant beamline(s) been run via `dodal connect ${BEAMLINE}`

2024-11-27 12:57 UTC, DominicOram requested changes
Great, thanks A few comments.

2024-11-27 12:57 UTC, DominicOram commented on src/mx_bluesky/hyperion/device_setup_plans/dcm_pitch_roll_mirror_adjuster.py
> +    )
Could: Rather than ask the device for it's settings based on the energy and then apply them in the plan could we just put it all into the device and allow us to do `mirror.set(energy_kev)` with the device handling the rest? This seems like it could be cleaner?

2024-11-27 12:57 UTC, DominicOram commented on src/mx_bluesky/hyperion/device_setup_plans/dcm_pitch_roll_mirror_adjuster.py
> +    yield from bps.wait(DCM_GROUP, timeout=30)
Could: Similar to above, given the `offest_mm` is now being done in the `undulator_dcm` should we do all these moves in the device side to avoid the logic being split over so many places?

2024-11-27 12:57 UTC, DominicOram commented on src/mx_bluesky/hyperion/device_setup_plans/dcm_pitch_roll_mirror_adjuster.py
> +        mirror.yaw_mrad, mirror_config["yaw_mrad"], wait=True, timeout=YAW_LAT_TIMEOUT_S
Should: It's misleading that the `LAT_TIMEOUT` is also being used on `yaw`

2024-11-27 12:57 UTC, DominicOram commented on src/mx_bluesky/hyperion/experiment_plans/robot_load_then_centre_plan.py
>          LOGGER.info("Pin not loaded, loading and centring")
Nit: Unrelated to this PR, I know but it's odd this message is logged after the fact

2024-11-27 12:57 UTC, DominicOram commented on src/mx_bluesky/hyperion/experiment_plans/robot_load_then_centre_plan.py
> +                demand_energy_ev / 1000,
Could: Given we're now doing this same logic in the robot load (the only other place this plan is called) maybe we could just change `set_energy_plan` to take an optional in `kev` and move the `if` and `/1000` into there?

2024-11-27 12:57 UTC, DominicOram commented on src/mx_bluesky/hyperion/experiment_plans/load_centre_collect_full_plan.py
> +    ), "Setting a different energy for gridscan and rotation is not supported"
Should: We should be able to support this quite easily. Can you make an issue for it?

2024-11-28 09:21 UTC, rtuck99 commented on src/mx_bluesky/hyperion/device_setup_plans/dcm_pitch_roll_mirror_adjuster.py
> +    # yaw, lat cannot be done simultaneously
Yaw and lat are compound axes of the front and back motors, so moving one will cancel any move of the other

2024-11-28 09:22 UTC, rtuck99 commented on src/mx_bluesky/hyperion/device_setup_plans/dcm_pitch_roll_mirror_adjuster.py
> +        mirror.yaw_mrad, mirror_config["yaw_mrad"], wait=True, timeout=YAW_LAT_TIMEOUT_S
That's why is called YAW_LAT_TIMEOUT and not LAT_TIMEOUT

2024-11-28 09:24 UTC, rtuck99 commented on src/mx_bluesky/hyperion/device_setup_plans/dcm_pitch_roll_mirror_adjuster.py
> +    )
The yaw and lat are part of the dcm, they change because of the mirror stripe change which is the VFM and a separate device, unless we want to roll up the VFM into the `undulator_dcm` to  make it `vfm_undulator_dcm`?

2024-11-28 09:28 UTC, rtuck99 commented on src/mx_bluesky/hyperion/device_setup_plans/dcm_pitch_roll_mirror_adjuster.py
> +    yield from bps.wait(DCM_GROUP, timeout=30)
I don't think it should be done in the undulator_dcm, I'm beginning to think the opposite, that the `undulator_dcm` should just be a dumb device and everything be orchestrated in this plan.

2024-11-28 09:34 UTC, rtuck99 commented on src/mx_bluesky/hyperion/experiment_plans/load_centre_collect_full_plan.py
> +    ), "Setting a different energy for gridscan and rotation is not supported"
#686

2024-11-28 10:09 UTC, rtuck99 commented on src/mx_bluesky/hyperion/experiment_plans/robot_load_then_centre_plan.py
> +                demand_energy_ev / 1000,
Yes, I should have done this - fewer tests and simpler code!

2024-11-29 15:29 UTC, DominicOram commented on src/mx_bluesky/hyperion/device_setup_plans/dcm_pitch_roll_mirror_adjuster.py
> +        mirror.yaw_mrad, mirror_config["yaw_mrad"], wait=True, timeout=YAW_LAT_TIMEOUT_S
D'oh, sorry

2024-11-29 15:54 UTC, DominicOram requested changes
Thanks. Still some comments, sorry.

2024-11-29 15:54 UTC, DominicOram commented on src/mx_bluesky/hyperion/device_setup_plans/dcm_pitch_roll_mirror_adjuster.py
> +    # yaw, lat cannot be done simultaneously
Great, thank, I've added this to the comment

2024-11-29 15:54 UTC, DominicOram commented on src/mx_bluesky/hyperion/device_setup_plans/dcm_pitch_roll_mirror_adjuster.py
> +    yield from bps.abs_set(dcm.offset_in_mm, offset_mm, wait=True)
Must: But, from memory, we needed that on the beamline because we needed the DCM energy to be set before we could set the DCM offset? So if we do this here we will need a wait for `UNDULATOR_GROUP` (which is poorly named as it is moving the DCM too) to finish first. I think that then costs us some time as we'll be ending up waiting on the undulator here too.

Should: Additionally, if we're going to do it here the `wait=True` is frustrating because AFAIK we don't need to wait on this to have finished before we start changing things on the mirrors as they're entirely separate devices.

General point: This is why I think we should push this further into the device, if we push it all the way into the DCM itself it's more obvious about what is the minimum thing we're waiting on.

2024-11-29 15:54 UTC, DominicOram commented on src/mx_bluesky/hyperion/device_setup_plans/dcm_pitch_roll_mirror_adjuster.py
> +    yield from bps.wait(DCM_GROUP, timeout=30)
I think it's cleaner to put all the logic for a particular device into the device so a plan just needs to do `yield from bps.set(dcm, energy)` and the dcm handles all of it's rolls/pitches etc. Especially as IMHO the asyncio syntax for ordering operations is cleaner than the `wait=GROUP` syntax. But I think either way that's outside of the scope here, sorry for bringing it up in the first place

2024-12-02 15:26 UTC, noemifrisina requested changes
lgtm, changes were addressed, please resolve the conflicts

2024-12-02 15:52 UTC, noemifrisina approved these changes

2024-12-02 15:52 UTC, merged