563 improved mx_bluesky parameter validation
DiamondLightSource/mx-bluesky pull request #689
Opened 2024-11-28 17:19 UTC by rtuck99

This addresses #563  and adds additional parameter validation to prevent invalid combinations of parameters.

It also adds PlantUML parameter class diagram to the docs generated by CI

2025-01-06 15:37 UTC, olliesilvester requested changes
This is nice!

Two things:
- The image displayed on the docs for the parameter hierarchy is very small, could we make it easier to read? 
![image](https://github.com/user-attachments/assets/f72979cd-d5c1-4274-83cc-9789592b36c3)

- This introduces a (small) extra step when building the docs locally. We now need to do:
```
python ./utility_scripts/generate_plantuml.py > docs/developer/hyperion/reference/param_hierarchy.puml
tox -e docs autobuild
```
Might be worth having a small utility script `locally_autobuild_docs` that does this for us

2025-01-06 15:37 UTC, olliesilvester commented on tests/unit_tests/hyperion/experiment_plans/test_load_centre_collect_full_plan.py
> +    params["multi_rotation_scan"]["rotation_scans"][1]["x_start_um"] = 3.0
I assume you meant to change x, y and z here

2025-01-08 12:28 UTC, rtuck99 commented
>     * This introduces a (small) extra step when building the docs locally. We now need to do:
> 
> 
> ```
> python ./utility_scripts/generate_plantuml.py > docs/developer/hyperion/reference/param_hierarchy.puml
> tox -e docs autobuild
> ```
> 

I've changed things so that instead of having an extra step in the github workflow, there is a pre-command step in the `tox` configuration so that `tox -e docs` now runs the generation automatically.

Unfortunately I can't do much about the page layout but you can open the diagram in a new tab and see it full size.

2025-01-08 13:31 UTC, olliesilvester approved these changes

2025-01-08 13:43 UTC, merged