I24 serial: Add some detector specific params in parameter model and beam center calculation
DiamondLightSource/mx-bluesky pull request #708
Opened 2024-12-10 17:27 UTC by noemifrisina

This should also take care of the beamcenter calculation.
UPDATE: This will not close #684 as it won't use the DetectorParams in the form they are now, but only add the property currently needed to the parameter model. 
Closes #647 

Needs [Dodal#955](https://github.com/DiamondLightSource/dodal/pull/955)
Needs also [Dodal#981](https://github.com/DiamondLightSource/dodal/pull/981)

2024-12-18 15:36 UTC, rtuck99 commented on src/mx_bluesky/beamlines/i24/serial/parameters/experiment_parameters.py
> +        directory = Path(self.visit) / self.directory
This property is accessed in 9 different places in production code, I don't think it should be creating the directory.

2024-12-19 10:52 UTC, rtuck99 commented
Ok, so I've had a bit of a think, and I think there are a number of problems with `DetectorParams` which we should address. I've written them up in
* DiamondLightSource/dodal#966

I'm reluctant to approve this PR because I think on balance on its own it makes things worse rather than better, in that it spreads usage of `DetectorParams` without addressing any of its shortcomings, and it also doesn't really use it enough to justify doing so.

I think a better approach would be to address part of DiamondLightSource/dodal#966 relating to the beam_xy_converter, make i24 and hyperion code both better in an incremental fashion.

2024-12-20 14:21 UTC, rtuck99 requested changes
See previous comment

2025-01-10 15:35 UTC, noemifrisina commented
After going through this PR with @rtuck99 and a lot of discussions on https://github.com/DiamondLightSource/dodal/issues/966, I've decided to revert all the changes using the current DetectorParams as that is going to be a separate big refactoring job in dodal - involving also the hyperion side of the code. This will be done in a separate branch to avoid holding up other work.

As for this PR, it now only instantiates the detector constants  needed in the parameter model in this PR, as well as uses the linear_interpolation_lut function from dodal to calculate the beam center position, which are the bits of DetectorParams needed by serial at this time.

2025-01-13 16:39 UTC, rtuck99 approved these changes
Approved. I await the next exciting instalment in this continuing saga

2025-01-17 11:39 UTC, merged