Use production grid detection plan in unit tests
DiamondLightSource/mx-bluesky pull request #721
Opened 2024-12-18 17:11 UTC by shihab-dls

This should fix issue #611, where we references to `_fake_grid_detection` have been removed and replaced with logic that runs the real grid detection plan.

2024-12-18 17:16 UTC, shihab-dls commented on tests/unit_tests/hyperion/experiment_plans/test_grid_detect_then_xray_centre_plan.py
> +    test_full_grid_scan_params.grid_width_um = 200
I realize that I had to change this parameter to achieve the correct number of triggers in the assertions.
I believe the underlying processes are the same, but the combination of mocked `bps.rd` values results in the difference in triggers that requires this change in `grid_width_um`.

Under the assumption that the underlying processes are the same, changing the asserted number of triggers to match that expected by the mocked `bps.rd` value seems reasonable. But I should look into what values are required for the expected number of triggers first...

2024-12-19 19:49 UTC, olliesilvester reviewed
Only had a quick glance, looks reasonable but I will check the values more thoroughly another time. Just one comment for now

2024-12-19 19:49 UTC, olliesilvester commented on tests/unit_tests/hyperion/experiment_plans/test_grid_detect_then_xray_centre_plan.py
> +    mock_rd.side_effect = _fake_generator_array(
Variable name is a little vague here - and it would be useful to have a comment explaining what each of these values refer to in the grid detection plan

2024-12-20 11:53 UTC, rtuck99 commented on tests/unit_tests/hyperion/experiment_plans/test_grid_detect_then_xray_centre_plan.py
> +    "mx_bluesky.hyperion.experiment_plans.oav_grid_detection_plan.bps.rd",
Intercepting all calls to bps.rd with a mock is pretty wild! I think there are better ways to do this

2024-12-20 14:17 UTC, rtuck99 commented
I've just pushed a commit with an outline sketch of what I think is a better way setup the test fixtures, that should make it more robust and enable more reuse

2024-12-20 14:23 UTC, rtuck99 requested changes
See above

2025-01-08 13:46 UTC, rtuck99 approved these changes
Approved

2025-01-08 13:51 UTC, merged